config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users

  root 'posts#index'

  get 'unauthorized' => 'posts#unauthorized'

  resources :posts
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord

  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :comments

  validates :image, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments

  def fullname
    [firstname.capitalize, lastname.capitalize].join(' ')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname, :email, :password, :password_confirmation])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@comment.post), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:content, :post_id, :user_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :own_the_post, only: [:edit, :update, :destroy]

  # Check if the user own the post
  def own_the_post
    @owner = Post.find(params[:id]).user

    redirect_to action: 'unauthorized' if @owner != current_user
  end

  def unauthorized

  end

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.page(params[:page]).per(1)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :publish_date, :heading, :body, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :can_update, only: [:update]

  def can_update
    redirect_to unauthorized_path if User.find(params[:id]) != current_user
  end

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:lastname, :firstname, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :comment_content %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.number_field :post_id, id: :comment_post_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.post_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      .profile-image{
        max-width: 50px;
        border: 4px solid #fff;
        border-radius: 100%;
        box-shadow: 0 2px 2px rgba(0,0,0,0.3);
        margin-bottom: 5px;
      }
    </style>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">

          <!-- Collapsed Hamburger -->
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
            <span class="sr-only">Toggle Navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <!-- Branding Image -->
          <a class="navbar-brand" href="<%= root_path %>">
            Blog
          </a>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
          <!-- Left Side Of Navbar -->
          <ul class="nav navbar-nav">
            &nbsp;
          </ul>

          <!-- Right Side Of Navbar -->
          <ul class="nav navbar-nav navbar-right pull-right">
            <!-- Authentication Links -->
            <% if user_signed_in? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                    <%= current_user.fullname %> <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                    <li>
                      <%= link_to "Logout", destroy_user_session_path, :method => "delete" %>
                    </li>
                    <hr>
                  </ul>
                </li>
            <% else %>
                <li><a href="<%= new_user_session_path %>">Login</a></li>
                <li><a href="<%= new_user_registration_path %>">Register</a></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3" >
    <div class="panel panel-default">
      <div class="panel-heading" >
        <h5 class="center"><%= form_title %></h5>
      </div>
      <div class="panel-body">
        <%= form_with(model: post, local: true) do |form| %>
            <% if post.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

                  <ul>
                    <% post.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>
            <div class="form-group">
              <%= form.label :title %>
              <%= form.text_field :title, id: :post_title, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :publish_date %>
              <%= form.datetime_select :publish_date, id: :post_publish_date, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :heading %>
              <%= form.text_area :heading, id: :post_heading, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :body %>
              <%= form.text_area :body, id: :post_body, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :image %>
              <%= form.file_field :image, id: :post_image, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :user_id %>
              <%= form.collection_select :user_id, User.all, :id, :fullname, class: "form-control" %>
            </div>
            <button class="btn btn-success center-block" type="submit">Envoyer</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'form', post: @post, form_title: 'Edit post' %>
<div class="center">
  <%= link_to 'Show', @post , class:"btn btn-default" %> |
  <%= link_to 'Back', posts_path, class:"btn btn-default" %>

</div>

app/views/posts/index.html.erb
<div class="center" style="margin-bottom: 25px">
  <h1>Posts</h1>
</div>

<% @posts.each do |post| %>
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="panel panel-default">
            <div class="panel-heading">
              <%= link_to post.title, post_path(post) %>
              (<%= post.comments.count %> comment)
              <% if !post.user.nil? %>
                  <%= link_to post.user.fullname, user_path(post.user), class: "pull-right" %>
              <% else %>
                  <span class="pull-right">Non renseigné</span>
              <% end %>
            </div>
            <div class="panel-body text-center">
              <h6><%= image_tag post.image.thumb.url, size: 30 %></h6>
              <h6><%= post.publish_date.strftime('%d/%m/%Y %H:%M') %></h6>
              <h5><%= post.heading %> </h5>
              <%= link_to 'Show', post, class: "btn btn-default" %>

              <% if current_user == post.user %>
                <%= link_to 'Edit', edit_post_path(post), class: "btn btn-default" %>
                <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
              <% end %>
            </div>
          </div>
        </div>
    </div>
<% end %>

<div class="center">
  <%= paginate @posts %>
</div>

<br>
<% if user_signed_in? %>
    <div class="center">
      <%= link_to 'New Post', new_post_path, class: "btn btn-default" %>
    </div>
<% end %>

app/views/posts/new.html.erb
<%= render 'form', post: @post, form_title: "New post" %>
<div class="center">
  <%= link_to 'Back', posts_path, class: "btn btn-default" %>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= link_to @post.title, post_path(@post) %>
        <%= link_to @post.user.fullname, user_path(@post.user), class: "pull-right" %>
      </div>
      <div class="panel-body">
        <ul>
          <li><h5><%= image_tag @post.image.thumb.url, size: 50 %></h5></li>
          <li><h5><%= @post.publish_date.strftime('%d/%m/%Y %H:%M') %></h5></li>
          <li><h5><%= @post.heading %></h5></li>
          <li><h5><%= @post.body %></h5></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<% @post.comments.each do |comment| %>
  <div class="row">
    <div class="col-lg-6 col-lg-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= link_to comment.user.fullname, user_path(@post.user) %>
        </div>
        <div class="panel-body">
          <%= comment.content %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<% if !current_user.nil? %>
  <div class="row">
    <div class="center col-lg-6 col-lg-offset-3 margin-button">
      <%= form_with(model: Comment.new, local: true, url: comments_path, class: "form-inline") do |f| %>
          <input type="hidden" name="comment[user_id]" value="<%= current_user.id %>">
          <input type="hidden" name="comment[post_id]" value="<%= @post.id %>">
          <%= f.text_field :content, class: "form-control", placeholder: "Content..." %>
          <button class="btn btn-success center-block" style="display: inline" type="submit">Send comment</button>
      <% end %>
    </div>
  </div>
<% end %>

<div class="center">
  <% if current_user == @post.user %>
    <%= link_to 'Edit', edit_post_path(@post), class: "btn btn-default" %> |
  <% end %>

  <%= link_to 'Back', posts_path, class: "btn btn-default margin-button" %>
</div>

app/views/posts/unauthorized.html.erb
<style>
  .parent {
    color: grey;
    height: 20em; /* hauteur du parent */
    line-height: 20em; /* hauteur de ligne (identique) */
  }
</style>

<div style="" class="parent">
  <div style="text-align: center; font-size: 70px;" >
    401
  </div>
  <div style="text-align: center; font-size: 70px;" >
    Unauthorized
  </div>
</div>

app/views/users/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3" >
    <div class="panel panel-default">
      <div class="panel-heading" >
        <h5 class="center"><%= form_title %></h5>
      </div>
      <div class="panel-body">
        <%= form_with(model: user, local: true) do |form| %>
          <% if user.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

                <ul>
                  <% user.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
          <% end %>
          <div class="form-group">
            <%= form.label :firstname %>
            <%= form.text_field :firstname, id: :user_firstname, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= form.label :lastname %>
            <%= form.text_field :lastname, id: :user_lastname, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= form.label :email %>
            <%= form.text_field :email, id: :user_email, class: "form-control" %>
          </div>
          <button class="btn btn-success center-block" type="submit">Envoyer</button>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render 'form', user: @user, form_title: 'Edit user'%>

<div class="center">
  <%= link_to 'Show', @user, class: "btn btn-default" %> |
  <%= link_to 'Back', users_path, class: "btn btn-default" %>
</div>

app/views/users/index.html.erb
<h1 style="text-align: center; margin-bottom: 20px">Users</h1>

<% @users.each do |user| %>
    <div class="row">
      <%= link_to user_path(user), class: "link" do %>
          <div class="col-md-6 col-md-offset-3">
            <div class="panel panel-default">
              <div class="panel-body text-center">
                <!--<img class="profile-img" src="/uploads/avatars/{{ $result->avatar }}">-->
                <h1> <%= user.firstname %></h1>
                <h5> <%= user.email %></h5>
              </div>
            </div>
          </div>
      <% end %>
    </div>
<% end %>

app/views/users/new.html.erb
<%= render 'form', user: @user, form_title: 'Create user' %>

<div class="center">
  <%= link_to 'Back', users_path, class: "btn btn-default" %>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-lg-8 col-lg-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <h4><%= @user.firstname.capitalize + " " + @user.lastname.capitalize %></h4>
      </div>
      <div class="panel-body">
        <ul>
          <li><h5><%= @user.email %></h5></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="center">
  <h2 style="margin-bottom: 25px">Posts of <%= @user.fullname %></h2>
</div>

<% @user.posts.each do |post| %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-default">
          <div class="panel-heading">
            <%= link_to post.title, post_path(post) %> <%= link_to post.user.fullname, user_path(post.user), class: "pull-right" %>
          </div>
          <div class="panel-body text-center">
            <h6><%= post.image %></h6>
            <h6><%= post.publish_date.strftime('%d/%m/%Y %H:%M') %></h6>
            <h5><%= post.heading %> </h5>
            <%= link_to 'Show', post, class: "btn btn-default" %>
            <% if current_user == post.user %>
              <%= link_to 'Edit', edit_post_path(post), class: "btn btn-default" %>
              <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
<% end %>

<div class="center">
  <%= link_to 'Edit', edit_user_path(@user), class: "btn btn-default" %> |
  <%= link_to 'Back', users_path, class: "btn btn-default" %>
</div>